console.log(typeof "x")
console.log(-(10-2))
console.log(3>2)
console.log(3<2)
console.log("Aardvark" != "Zoroaster")
console.log("Itchy" != "Scratchy")
console.log("Apple" == "Orange")
console.log(NaN == NaN)
console.log(true && false)
console.log(true && true)
console.log(false || true)
console.log(false || false)
console.log(true ? 1 : 2)
console.log(false ? 1 : 2)